version: 0.2

env:
  variables:
    BEANSTALK_BUCKET: "ppa-artifacts"
    BEANSTALK_APP: "PPA"
    BEANSTALK_ENVIRONMENT: "development-ng"

phases:
  install:
    runtime-versions:
      java: "corretto17"
  build:
    commands:
    - echo "Files:"
    - find .
    - sh ./cicd/deploy/deploy-to-beanstalk.sh
